export const data = {
  "2zd33b8c": {
    name: "Leche GLORIA 400g Paquete 6 und.",
    id: "2zd33b8c",
    sku: "199315",
    price: 21.6,
    image: "",
    attributes: {
      description:
        "Leche evaporada, presentacion en lata 400 g. Paquete de 6 und.",
      tipo: "Lacteos",
      presentacion: "Six pack",
      contenido: "6 latas",
    },
  },
  "8t6yfd9e": {
    name: "Arroz Extra Costeño Bolsa 5Kg",
    id: "8r6yfd9e",
    sku: "641425",
    price: 21.3,
    image: "",
    attributes: {
      description: "Variedad extra graneadito",
      tipo: "Abarrotes",
      presentacion: "Bolsa",
      contenido: "5Kg",
    },
  },
  "2e9rth65": {
    name: "Pack Detergente ACE + Lavavajillas AYUDIN 1.2L",
    id: "2e9rth65",
    sku: "K0000002974",
    price: 31.9,
    image: "",
    attributes: {
      description:
        "Detergente ACE 2Kg y lavavajillas liquido limon botella de 1.2L",
      tipo: "Limpieza",
      presentacion: "Bolsa/Botella",
      contenido: "2und.",
    },
  },
  "8t5hgf15": {
    name: "Jamon Pizza Paquete 370g",
    id: "8t5hgf15",
    sku: "K0000002974",
    price: 12.29,
    image: "",
    attributes: {
      description: "Queso semiduro y jamon pizza 370 g",
      tipo: "Embutidos",
      presentacion: "Paquete",
      contenido: "2und.",
    },
  },
  "7g65fd9r": {
    name: "Jamon Pizza Paquete 370g",
    id: "7g65fd9r",
    sku: "995414",
    price: 4.09,
    image: "",
    attributes: {
      description: "Fuente de nutrientes, minerales y hierro",
      tipo: "Menestras",
      presentacion: "Bolsa",
      contenido: "500g",
    },
  },
  "5s8fsd22": {
    name: "Yogurt Gloria 1.9Kg",
    id: "5s8fsd22",
    sku: "20190924",
    price: 4.09,
    image: "",
    attributes: {
      description: "Yogurt bebible sabor a fresa en galonera de 1.9Kg",
      tipo: "Lacteos",
      presentacion: "Galonera",
      contenido: "1.9Kg",
    },
  },
  "85sf9d8e": {
    name: "Azucar Casa Grande Bolsa 1Kg",
    id: "85sf9d8e",
    sku: "20197283",
    price: 5.4,
    image: "",
    attributes: {
      description: "Azucar rubia contenido 1kg Casa Grande",
      tipo: "Abarrotes",
      presentacion: "Bolsa",
      contenido: "1Kg",
    },
  },
  "5d8jmn2b": {
    name: "Ricocan adultos Bolsa 15Kg",
    id: "5d8jmn2b",
    sku: "20197283",
    price: 120.9,
    image: "",
    attributes: {
      description: "Azucar rubia contenido 1kg Casa Grande",
      tipo: "Abarrotes",
      presentacion: "Bolsa",
      contenido: "1Kg",
    },
  },
};
